#                                                                        #
# Configuration for the FLOW3 Framework                                  #
#                                                                        #
# This file contains additions to the base configuration for the FLOW3   #
# Framework. Just add your own modifications as necessary.               #
#                                                                        #
# Please refer to the default configuration file or the FLOW3 manual for #
# possible configuration options.                                        #
#                                                                        #

FLOW3:
  configuration:
    compileConfigurationFiles: y
  
  log:
    systemLogger:
      backendOptions: { logFileURL: %FLOW3_PATH_DATA%Logs/%FLOW3_SAPITYPE%/FLOW3_Production.log, createParentDirectories: y, severityThreshold: %LOG_WARNING% }
