#                                                                        #
# Configuration for the FLOW3 Framework                                  #
#                                                                        #
# This file contains additions to the base configuration for the FLOW3   #
# Framework in the Testing context. Just add your own modifications      #
# as necessary.                                                          #
#                                                                        #
# Please refer to the default configuration file or the FLOW3 manual for #
# possible configuration options.                                        #
#                                                                        #

FLOW3:
  aop:
    enable: n

  persistence:
    enable: n
